/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
      colors: {
        "on-secondary-fixed-variant": "#2e4770",
        "surface-variant": "#d8e3fb",
        "on-background": "#111c2d",
        "surface": "#f9f9ff",
        "surface-tint": "#005cba",
        "primary": "#005ab5",
        "on-error": "#ffffff",
        "secondary": "#465f8a",
        "primary-fixed": "#d7e3ff",
        "on-error-container": "#93000a",
        "outline": "#717785",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdcc4",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb781",
        "surface-container-highest": "#d8e3fb",
        "tertiary-container": "#b35e00",
        "on-primary-container": "#fefcff",
        "surface-container-high": "#dee8ff",
        "inverse-primary": "#aac7ff",
        "outline-variant": "#c1c6d6",
        "on-primary": "#ffffff",
        "secondary-container": "#b4cdfe",
        "primary-fixed-dim": "#aac7ff",
        "on-tertiary-fixed-variant": "#6f3800",
        "inverse-on-surface": "#ecf1ff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container": "#e7eeff",
        "surface-container-low": "#f0f3ff",
        "on-secondary-fixed": "#001b3e",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#2f1400",
        "on-surface-variant": "#414753",
        "on-surface": "#111c2d",
        "secondary-fixed": "#d7e3ff",
        "primary-container": "#0472e2",
        "surface-dim": "#cfdaf2",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#00458e",
        "surface-bright": "#f9f9ff",
        "inverse-surface": "#263143",
        "on-primary-fixed": "#001b3e",
        "secondary-fixed-dim": "#aec7f8",
        "on-secondary-container": "#3e5681",
        "tertiary": "#8f4a00",
        "on-tertiary": "#ffffff"
      },
  },
  plugins: [],
}

